os: linux
dist: bionic
language: c
compiler:
- gcc
branches:
  only:
  - master
  - "/^v.*$/"
addons:
  apt:
    packages:
    - fakeroot
    - p7zip-full
    - libtool-bin
    - gperf
    - texinfo
    - python-docutils
    - autopoint
before_script:
- "./trunk/tools/shellcheck.sh"
- mkdir -p /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x && mkdir -p /opt/images/
- rm -rf toolchain-mipsel/ && mv -f * .[^.]* /opt/rt-n56u
- curl -LO $toolchain_url && tar -xf mipsel-linux-uclibc.tar.xz -C /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
- ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/
script:
- for m in $targets; do fakeroot ./build_firmware_ci $m;
  if [ $? = 0 ]; then cp -f images/*.trx /opt/images/$m.trx; else exit 1; fi;
  ./clear_tree_simple >/dev/null 2>&1; done
env:
  jobs:
  - build_variant=mt7621 targets="K2P_nano K2P_nano-5.0 K2P-5.0"
  global:
  - toolchain_url="https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz"
git:
  depth: 3
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: "/opt/images/*.trx"
  on:
    repo: nodece/k2p-padavan
